/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;
import java.util.ArrayList;
/**
 *
 * @author Илья
 */
public class tabs extends javax.swing.JFrame {
    ArrayList<RecIntegral> list = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tabs.class.getName());

    /**
     * Creates new form tabs
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton4 = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        CalculateButton = new javax.swing.JButton();
        integralName = new javax.swing.JLabel();
        Table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        VPtext = new javax.swing.JLabel();
        NPtext = new javax.swing.JLabel();
        StepText = new javax.swing.JLabel();
        NPtextfield = new javax.swing.JTextField();
        VPtextfield = new javax.swing.JTextField();
        StepTextfield = new javax.swing.JTextField();
        ClearTable = new javax.swing.JButton();
        BackCollection = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton4.setText("Добавить ");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setSize(new java.awt.Dimension(452, 420));

        addButton.setText("Добавить ");
        addButton.addActionListener(this::addButtonActionPerformed);

        DeleteButton.setText("Удалить");
        DeleteButton.addActionListener(this::DeleteButtonActionPerformed);

        CalculateButton.setText("Вычислить");
        CalculateButton.addActionListener(this::CalculateButtonActionPerformed);

        integralName.setText("1/x");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "НП", "ВП", "Шаг", "Результат"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setViewportView(jTable1);

        VPtext.setText("ВП");

        NPtext.setText("НП");

        StepText.setText("Шаг");

        VPtextfield.addActionListener(this::VPtextfieldActionPerformed);

        ClearTable.setText("Очистить таблицу");
        ClearTable.addActionListener(this::ClearTableActionPerformed);

        BackCollection.setText("Восстановить коллекцию");
        BackCollection.addActionListener(this::BackCollectionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(integralName)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NPtext)
                            .addComponent(StepText)
                            .addComponent(VPtext))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VPtextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(StepTextfield)
                            .addComponent(NPtextfield))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BackCollection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClearTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CalculateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(integralName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VPtext)
                            .addComponent(VPtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NPtext)
                            .addComponent(NPtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteButton)
                            .addComponent(ClearTable))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StepText)
                            .addComponent(StepTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CalculateButton))
                        .addGap(37, 37, 37)
                        .addComponent(Table, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BackCollection))
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1){
            list.remove(selectedRow);
            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);
        }else {
            javax.swing.JOptionPane.showMessageDialog(this, "Choose, delete row!");
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
         try {
        double a = Double.parseDouble(NPtextfield.getText());
        double b = Double.parseDouble(VPtextfield.getText());
        double h = Double.parseDouble(StepTextfield.getText());

        // создаём объект и проверяем
        RecIntegral rec = new RecIntegral(a, b, h, 0);
        list.add(rec);

        javax.swing.table.DefaultTableModel model = 
                (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{a, b, h, 0});

    } catch (InvalidRecIntegralException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(),
                "Некорректные данные", javax.swing.JOptionPane.WARNING_MESSAGE);
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Введите корректные числа",
                "Ошибка ввода", javax.swing.JOptionPane.WARNING_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Произошла ошибка: " + e.getMessage(),
                "Ошибка", javax.swing.JOptionPane.ERROR_MESSAGE);
    }   
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTableActionPerformed
        javax.swing.table.DefaultTableModel model = 
                (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_ClearTableActionPerformed

    private void BackCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackCollectionActionPerformed
        javax.swing.table.DefaultTableModel model= 
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (RecIntegral r : list){
            
            model.addRow(new Object[]{
            r.a,
            r.b,
            r.h,
            r.result,
        });
        }
    }//GEN-LAST:event_BackCollectionActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void VPtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VPtextfieldActionPerformed
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            

        java.awt.EventQueue.invokeLater(() -> new tabs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackCollection;
    private javax.swing.JButton CalculateButton;
    private javax.swing.JButton ClearTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel NPtext;
    private javax.swing.JTextField NPtextfield;
    private javax.swing.JLabel StepText;
    private javax.swing.JTextField StepTextfield;
    private javax.swing.JScrollPane Table;
    private javax.swing.JLabel VPtext;
    private javax.swing.JTextField VPtextfield;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel integralName;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}